name = "pl-fantasy-dashboard"
main = "src/index.ts"
compatibility_date = "2025-01-31"
type = "javascript"

[build]
command = "npm run build"
cwd = "./"
watch_paths = ["src/**/*.ts", "src/**/*.tsx"]

[env.production]
routes = [
  { pattern = "https://fpl.krueger.app/*", zone_name = "krueger.app" }
]
vars = { LEAGUE_ID = "105341" }

[build.upload]
format = "modules"
main = "src/index.ts"
